[build]
  command = "npm run build"
  functions = "functions"
  publish = "build"

# if this doesn't work put '/* /index.html 200' in a '_redirects' file in public folder
[[redirects]]
  from = "/*"
  to "/index.html"
  status = 200